# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Unfortunately Github's dependabot does not support specifying wildcard/glob patterns yet (see https://github.com/dependabot/dependabot-core/issues/2178)
# so we have to manually specify all the projects we want dependabot to monitor for now

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/clients/python/vue-avis-client"
    schedule:
      interval: "weekly"
